project:
  type: book

book:
  title: "etoile348"
  subtitle: "cuisine"
  author: "granPiero"
  date: now
  chapters:
    - index.qmd
    - intro.qmd
    - BOM.qmd
    - fournisseur.qmd
    - etoile_rooms.qmd
    - plans.qmd

format:
  pdf:
    documentclass: scrreprt
    geometry: "left=2cm,right=2cm,top=1cm,bottom=1cm"
  html:
    theme: cosmo
editor: visual

